config/routes.rb
Rails.application.routes.draw do
resources :uploaded_files

  devise_for :users

  resources :songs

  get 'test/index'

  get 'welcome/index'

  root 'welcome#index'
  get 'welcome/play' => 'welcome#play', as: :play_song
  get 'welcome/download' => 'welcome#download', as: :download
  get 'welcome/audio_download/:id' => 'welcome#audio_download', as: :download_audio

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      @user = User.find_or_create_by(:id => user.id)
      if @user.admin?
        can :manage, :all
      else
        can :index, Song
      end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/song.rb
class Song < ActiveRecord::Base

end

app/models/uploaded_file.rb
class UploadedFile < ActiveRecord::Base
  has_attached_file :audio,
                    :path => ":rails_root/public/:attachment/:basename.:extension",
                    :url => ":rails_root/public/:attachment/:basename.:extension"
  validates_attachment_presence :audio
  validates_attachment_content_type :audio, :content_type => [ 'application/mp3', 'application/x-mp3', 'audio/mpeg', 'audio/mp3' ],
                                    :message => 'file must be of filetype .mp3'



end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :audio_files
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates_uniqueness_of :username
  validates_presence_of :username
  validates :username, presence: true, length: {maximum: 255}, uniqueness: { case_sensitive: false }, format: { with: /\A[a-zA-Z0-9]*\z/, message: "Solo puede contener letras y numeros." }
  attr_accessor :login


  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["username = :value OR lower(email) = lower(:value)", { :value => login }]).first
    else
      where(conditions).first
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :configure_devise_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception

  def authorize_admin
    redirect_to root_path, alert: 'Acceso Denegado' unless (can? :create, UploadedFile)
  end
  def update_song
    p "Actualizadas las canciones-------------------------------------------------------------------"
  end
  protected
  def configure_devise_permitted_parameters
    registration_params = [:first_name,:last_name,:username, :email, :password, :password_confirmation]
    if params[:action] == 'update'
      devise_parameter_sanitizer.for(:account_update) {
          |u| u.permit(registration_params << :current_password)
      }
    elsif params[:action] == 'create'
      devise_parameter_sanitizer.for(:sign_up) {
          |u| u.permit(registration_params)
      }
    end
  end

end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit, :update]
  load_and_authorize_resource

  # GET /songs
  # GET /songs.json
  def index
    @songs = Song.all
  end
  def new
    @song = Song.new
  end

  # GET /songs/1
  # GET /songs/1.json
  def show
  end


  # GET /songs/1/edit
  def edit
  end

  # PATCH/PUT /songs/1
  # PATCH/PUT /songs/1.json
  def update
    respond_to do |format|
      if @song.update(song_params)
        format.html { redirect_to @song, notice: 'Song was successfully updated.' }
        format.json { render :show, status: :ok, location: @song }
      else
        format.html { render :edit }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_song
      @song = Song.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def song_params
      params.require(:song).permit(:name, :path, :played, :recorded_date, :downloaded_times, :attachment)
    end
end

app/controllers/test_controller.rb
class TestController < ApplicationController
  def index
  end
end

app/controllers/uploaded_files_controller.rb
class UploadedFilesController < ApplicationController
  before_filter :authorize_admin
  before_action :set_uploaded_file, only: [:show, :edit, :update, :destroy]
  after_action :update_song, :only => [:create]
  # GET /uploaded_files
  # GET /uploaded_files.json
  def index
    @uploaded_files = UploadedFile.all
  end

  # GET /uploaded_files/1
  # GET /uploaded_files/1.json
  def show
  end

  # GET /uploaded_files/new
  def new
    @uploaded_file = UploadedFile.new
  end

  # GET /uploaded_files/1/edit
  def edit
  end

  # POST /uploaded_files
  # POST /uploaded_files.json
  def create
    @uploaded_file = UploadedFile.new(uploaded_file_params)

    respond_to do |format|
      if @uploaded_file.save
        system "rake songs:update"
        format.html { redirect_to @uploaded_file, notice: 'Uploaded file was successfully created.' }
        format.json { render :show, status: :created, location: @uploaded_file }
      else
        format.html { render :new }
        format.json { render json: @uploaded_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /uploaded_files/1
  # PATCH/PUT /uploaded_files/1.json
  def update
    respond_to do |format|
      if @uploaded_file.update(uploaded_file_params)
        format.html { redirect_to @uploaded_file, notice: 'Uploaded file was successfully updated.' }
        format.json { render :show, status: :ok, location: @uploaded_file }
      else
        format.html { render :edit }
        format.json { render json: @uploaded_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /uploaded_files/1
  # DELETE /uploaded_files/1.json
  def destroy
    @uploaded_file.destroy
    respond_to do |format|
      format.html { redirect_to uploaded_files_url, notice: 'Uploaded file was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_uploaded_file
    @uploaded_file = UploadedFile.find(params[:id])
  end

 def make_song_playable

 end
  # Never trust parameters from the scary internet, only allow the white list through.
  def uploaded_file_params
    params.require(:uploaded_file).permit(:audio)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :set_song, only: [:play, :audio_download, :download]
  def index
    @songs = Song.all

  end
  def play
    @song.played =@song.played+1
    @song.save
    render json: {"id"=> @song.id, played: @song.played}, :callback => params[:callback]
  end
  def audio_download
    @song.downloaded_times+=1
    @song.save
    send_file "#{Rails.root}/public/#{@song.path}/#{@song.name}.mp3", :x_sendfile => true, type: "audio/mp3", filename: @song.name+".mp3"
  end
  def download
    @song.downloaded_times+=1
    @song.save
    render json: {"id"=> @song.id, downloaded_times: @song.downloaded_times }, :callback => params[:callback]
  end
  private

  def set_song
    @song = Song.find(params[:id])
  end

  def song_params
    params.require(:song).permit(:name, :path, :played, :recorded_date, :downloaded_times)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/test_helper.rb
module TestHelper
end

app/helpers/uploaded_files_helper.rb
module UploadedFilesHelper
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Alabanza Fuente de Vida</title>
  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'bootstrap.js' %>
  <script src="http://use.fonticons.com/d94948c7.js"></script>
  <%= csrf_meta_tags %>

</head>
<body>
<nav class="navbar palette-belize-hole navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <%= link_to "Alabanza FdV", root_path, class: "navbar-brand" %>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li>
          <%= link_to "Grabaciones", songs_path %>
        </li>
        <% if can? :new, UploadedFile %>
            <li>
              <%= link_to "Agregar audio", new_uploaded_file_path %>
            </li>
        <% end %>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if signed_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <%= current_user.try(:username) %> <strong class="caret"></strong></a>
              <ul class="dropdown-menu">
                <!--<li>-->
                  <!--<a href="#">Action</a>-->
                <!--</li>-->
                <!--<li>-->
                  <!--<a href="#">Another action</a>-->
                <!--</li>-->
                <!--<li>-->
                  <!--<a href="#">Something else here</a>-->
                <!--</li>-->
                <li class="divider">
                </li>
                <li>
                  <%= link_to 'Desconectarme', destroy_user_session_path, method: :delete %>
                </li>
              </ul>
            </li>
        <% else %>
            <li> <%= link_to "Registrarme", new_user_registration_path %> </li>
            <li>
              <%= link_to 'Conectarme', new_user_session_path %>
            </li>

        <% end %>
      </ul>

    </div>
  </div>
</nav>
<!--<div id="logo">-->
<!--<%= image_tag "fdv_logo.png",:class=> "img-responsive"%>-->
<!--</div>-->



<div class="container-fluid">
  <% flash.each do |name, msg| %>
      <%= content_tag :div, class: "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do %>
          <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
          <%= msg %>
      <% end %>
  <% end %>

  <%= yield %>
  <footer class="navbar palette-belize-hole navbar-inverse navbar-fixed-bottom" style="margin-top: 35px;">
    <ul class="nav navbar-nav">
      <li><a id="audio"></a></li>
      <li> <a id="nowplaying"></a></li>
    </ul>
  </footer>
</div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/wavesurfer.js/1.0.57/wavesurfer.min.js"></script>
</body>
</html>

app/views/songs/_form.html.erb
<%= form_for(@song, html: { class: "form-horizontal", role: "form" }) do |f| %>
    <% if @song.errors.any? %>
        <div class="alert alert-danger alert-dismissable" role="alert">
          <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
          <h4><%= pluralize(@song.errors.count, "error") %> prohibited this song from being saved:</h4>
          <ul>
            <% @song.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="form-group">
      <%= f.label :name, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_field :name, class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :path, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_field :path, class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :played, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.number_field :played, class: "form-control" %>
      </div>
    </div>
    <% if signed_in? %>
        <% if current_user.admin? %>
            <div class="form-group">
              <%= f.label :recorded_date, class: "col-sm-2 control-label" %>
              <div class="col-sm-10">
                <%= f.date_select :recorded_date, class: "form-control" %>
              </div>
            </div>
        <% end %>
    <% end %>
    <div class="form-group">
      <%= f.label :downloaded_times, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.number_field :downloaded_times, class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit class: "btn btn-primary" %>
      </div>
    </div>
<% end %>

app/views/songs/edit.html.erb
<div class="page-header">
  <%= link_to songs_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @song, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing song</h1>
</div>

<%= render 'form' %>

app/views/songs/new.html.erb
<div class="page-header">
  <%= link_to songs_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New song</h1>
</div>

<%= render 'form' %>

app/views/songs/show.html.erb
<div class="page-header">
  <%= link_to songs_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_song_path(@song), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show song</h1>
</div>

<dl class="dl-horizontal">
  <dt>Name:</dt>
  <dd><%= @song.name %></dd>

  <dt>Path:</dt>
  <dd><%= @song.path %></dd>

  <dt>Played:</dt>
  <dd><%= @song.played %></dd>

  <dt>Recorded date:</dt>
  <dd><%= @song.recorded_date %></dd>

  <dt>Downloaded times:</dt>
  <dd><%= @song.downloaded_times %></dd>

</dl>

app/views/uploaded_files/_form.html.erb
<%= form_for(@uploaded_file, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @uploaded_file.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@uploaded_file.errors.count, "error") %> prohibited this uploaded_file from being saved:</h4>

      <ul>
      <% @uploaded_file.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :audio, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.file_field :audio, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/uploaded_files/edit.html.erb
<div class="page-header">
  <%= link_to uploaded_files_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @uploaded_file, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing uploaded_file</h1>
</div>

<%= render 'form' %>

app/views/uploaded_files/index.html.erb
<div class="page-header">
  <%= link_to new_uploaded_file_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Uploaded file
  <% end %>
  <h1>Listing uploaded_files</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Audio</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @uploaded_files) do |uploaded_file| %>
            <td><%= uploaded_file.audio %></td>
            <td><%= link_to 'Show', uploaded_file %></td>
        <td><%= link_to 'Edit', edit_uploaded_file_path(uploaded_file) %></td>
        <td><%= link_to 'Destroy', uploaded_file, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/uploaded_files/new.html.erb
<div class="page-header">
  <%= link_to uploaded_files_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New uploaded_file</h1>
</div>

<%= render 'form' %>

app/views/uploaded_files/show.html.erb
<div class="page-header">
  <%= link_to uploaded_files_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_uploaded_file_path(@uploaded_file), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show uploaded_file</h1>
</div>

<dl class="dl-horizontal">
  <dt>Audio:</dt>
  <dd><%= @uploaded_file.audio %></dd>

</dl>

app/views/welcome/index.html.erb
<div class="row">
  <div class="col-md-12">
    <%= image_tag "fdv_logo.png",:class=> "text-center", :width => 350 %>
  </div>
</div>
<script>
  window.setTimeout(function(){

    // Move to a new location or you can do something else
    window.location.href = "<%= songs_path %>";

  }, 3000);
</script>